config/routes.rb
Juntus::Application.routes.draw do

  get "dashboard" => "users#dashboard"
  get "quem_somos"            => "welcome#quem_somos"
  
  match '/auth/:provider/callback', to: 'sessions#create', :as => :auth_callback
  match "/auth/failure" => "sessions#failure", :as => :auth_failure
  match "/logout" => "sessions#destroy", :as => :logout

  post "/ideas/:idea_id/register" => "registrations#register", :as => :register_idea

  resources :ideas, :path_names => { :new => 'nova', :edit => 'editar' }

  root :to => 'ideas#index'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :description, :short_description, :title, :logo, :background
  
  validates :title, :description, :short_description, :user_id, presence: true
  
  has_many :registrations
  has_many :users, :through => :registrations
  belongs_to :owner, :class_name => User, :foreign_key => :user_id
  
  has_attached_file :logo, 
                    :styles => { :medium => "216x216>", :thumb => "100x100>" },
                    :storage => :s3,
                    :bucket => ENV['AMAZON_S3_BUCKET'],
                    :path => "logos/:id.:style.:extension",
                    :s3_credentials => {
                      :access_key_id => ENV['AMAZON_ACCESS_KEY_ID'],
                      :secret_access_key => ENV['AMAZON_SECRET_ACCESS_KEY']
                    }
                    
  has_attached_file :background, 
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :storage => :s3,
                    :bucket => ENV['AMAZON_S3_BUCKET'],
                    :path => "backgrounds/:id.:style.:extension",
                    :s3_credentials => {
                      :access_key_id => ENV['AMAZON_ACCESS_KEY_ID'],
                      :secret_access_key => ENV['AMAZON_SECRET_ACCESS_KEY']
                    }
  
  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea

  attr_accessible :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :access_token, :email, :name, :provider, :uid
  
  validates :name, :email, presence: true
  
  has_many :ideas
  has_many :registrations
  has_many :ideas
  
  def self.find_or_create_with_omniauth(auth)
    user = self.find_or_create_by_provider_and_uid(auth["provider"], auth["uid"])
    user.assign_attributes({:name => auth["info"]["name"], :email => auth["info"]["email"], :access_token => auth["credentials"]["token"], :photo_url => auth["info"]["image"]}, :without_protection => true)
    user.save(:validate => false)
    user
  end
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :user_signed_in?
  before_filter :save_return_path
  
  private
  def save_return_path
    session[:return_path] = request.path
  end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    !current_user.nil?
  end
  
  def authenticate!
    user_signed_in? || redirect_to((request.env["HTTP_REFERER"].blank?) ? root_path : :back, :alert => "Você precisa estar logado...")
  end
end

app/controllers/ideas_controller.rb
# -*- encoding : utf-8 -*-
class IdeasController < ApplicationController
  before_filter :authenticate!, :except => [:index, :show]
  
  def edit
    @idea = current_user.ideas.find(params[:id])
  end
  
  def update
    @idea = current_user.ideas.find(params[:id])
    if @idea.update_attributes(params[:idea])
      redirect_to root_path, :notice => "Atualizado com sucesso!"
    else
      render "edit"
    end
  end

  def new
    @idea = Idea.new
  end
  
  def create
    @idea = current_user.ideas.new(params[:idea])

    if @idea.save
      redirect_to @idea, notice: 'Ideia criada com sucesso.'
    else
      render 'new'
    end  
  end
  
  def show
    @idea = Idea.find(params[:id])
  end
  
  def index
    @ideas = Idea.all.sample(Idea.count)
  end
end

app/controllers/registrations_controller.rb
# encoding: utf-8
class RegistrationsController < ApplicationController
  before_filter :require_authentication!
  
  def register
    idea.registrations.find_or_create_by_user_id(current_user.id)
    
    redirect_to idea
  end
  
  private 
    def require_authentication!
      return redirect_to idea, :alert => "Você precisa estar logado!!" unless current_user
    end
    
    def idea
      @idea ||= Idea.find(params[:idea_id])
    end
end

app/controllers/sessions_controller.rb
# -*- encoding : utf-8 -*-
class SessionsController < ApplicationController
  skip_before_filter :save_return_path
  
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_or_create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to redirect_path, notice: "Opa! Você está online!"
  end

  def failure
    redirect_to root_url, :alert => 'Não foi possível autenticar, tente novamente.'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Hum... Volte em breve!"
  end
  
  private
  def redirect_path
    session[:return_path] || root_path
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate!
  
  def dashboard
    @user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def quem_somos
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ideas/_form.html.haml
= form_for @idea, :html => { :multipart => true } do |f|
  %p
    = f.label :title, 'Título'
    = f.text_field :title
  %p  
    = f.label :short_description, 'Descrição Curta'
    = f.text_area :short_description, :rows => 2
  %p  
    = f.label :description, 'Descrição Completa'
    = f.text_area :description, :rows => 5, :cols => 70
  %p
    = f.label :logo, 'Logo'
    = f.file_field :logo
  %p
    = f.label :background, 'Background'
    = f.file_field :background
  %p  
    = f.submit nil, :class => "btn btn-inverse btn-large"

app/views/ideas/_idea.html.haml
%li
  .idea-title
    %h4= link_to idea.title, idea
    .shadow
  = link_to idea do
    .idea-image{:style => "background-image: url(#{idea.logo.url(:medium)})"}
    %p.desc= idea.short_description

app/views/ideas/edit.html.haml
.row
  .content.span12
    %h2 Editar Idéia
    = render "form"

app/views/ideas/index.html.haml
= content_for :phrase do
  .desc.span8.offset2
    %p Pensado para ser um site de código fonte aberto, rodando para todo o Brasil, o Junt.us oferece espaço para criação e divulgação de idéias

.row-fluid
  .span12
    %ul#ideas
      = render @ideas

app/views/ideas/new.html.haml
.row
  .content.span12
    %h2 Nova Idéia
    = form_for @idea, :html => { :multipart => true } do |f|
      %p
        = f.label :title, 'Título'
        = f.text_field :title
      %p  
        = f.label :short_description, 'Descrição Curta'
        = f.text_area :short_description, :rows => 2
      %p  
        = f.label :description, 'Descrição Completa'
        = f.text_area :description, :rows => 5, :cols => 70
      %p
        = f.label :logo, 'Logo'
        = f.file_field :logo
      %p
        = f.label :background, 'Background'
        = f.file_field :background
      %p  
        = f.submit "Criar idéia", :class => "btn btn-inverse btn-large"

app/views/ideas/show.html.haml
.row
  .content.span12.idea-content
    .idea-header
      = image_tag(@idea.logo.url("medium"), :class => "idea-image", :width => "200")
      .inner.row
        .span7.offset3.idea-title
          %h2= @idea.title
          %p= @idea.short_description
        .span2.idea-button
          = link_to image_tag("participate_button.png"), register_idea_path(@idea), :method => :post
    .idea-body.row-fluid
      .inner
        .span8
          = simple_format(@idea.description)
          .fb-comments{"data-href" => idea_url(@idea), "data-num-posts" => "2"}
        
        %aside.span4
          .registered_count
            .counter= @idea.registrations.count
            participantes
          .comment_count
            .counter<
              %fb:comments-count{"href" => idea_url(@idea)}
            comentários
        
          %h5 participantes
          %ul.registered_list
            - @idea.users.each do |user|
              %li
                = image_tag(user.photo_url, :class => "img-circle")
                = user.name

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "pt"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %meta{:name => "keywords", :content => ""}
    %meta{:name => "description", :content => ""}

    %title= yield(:title) + " | Junt.us"

    %link{:href => "/favicon.png", :rel => "shortcut icon"}
    = yield(:header_tags)

    = stylesheet_link_tag "application", :type => nil, :media => "all"
    = csrf_meta_tags

    /[if lt IE 9]
      %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}

  %body
    .container-fluid
      = render "/shared/header"
      = render "/shared/flashes"

      %hr
      %section{:role => "main"}
        = yield

      = render "/shared/footer"
      = javascript_include_tag "application", :type => nil
      = render "/shared/ga"
      = render "/shared/fb"

app/views/shared/_fb.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%= ENV['FACEBOOK_KEY'] %>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/shared/_flashes.html.haml
.row-fluid
  .span8.offset2
    - if notice
      %p.notice
        = notice
    - if alert
      %p.alert
        = alert

app/views/shared/_footer.html.haml
%footer
  %ul.footer-links
    %li.title= link_to 'junt.us', root_url
    %li= link_to 'quem somos', quem_somos_url
    %li= link_to 'como funciona', '#'
    %li= link_to 'todas as idéias', ideas_url
    %li= link_to 'contato', '#'
  .copy
    = "Copyright &copy; 2012 junt.us".html_safe

app/views/shared/_ga.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'XXXXX-XXXX']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_header.html.haml
%header
  .row-fluid
    .header-inner.span10.offset1
      #login
        - if current_user
          %p
            = "Bem-vindo <strong>#{link_to current_user.name, dashboard_path}</strong> &bull; ".html_safe
            = link_to "Sair", logout_path
        - else
          = link_to "Acesse com Facebook", "/auth/facebook", :id => "facebook-connect"
        %br
        = link_to image_tag("botao_mais_ideia.png"), new_idea_path, :id => "new-idea-button"
        
      #logo
        %h1= link_to "Junt.us", root_url
        
  .row-fluid
    = yield :phrase

app/views/users/dashboard.html.haml
.profile
  .row
    .content.span12
    
      = image_tag(@user.photo_url, height: "200px", :class => "thumbnail")
      %h1= @user.name

      %br
      %h2 Minhas idéias

      - @user.ideas.each do |idea|
        .idea
          = image_tag idea.logo.url(:medium), :width => "140"
          %h2= link_to idea.title, edit_idea_path(idea)
          %p= idea.short_description
      - unless @user.ideas.any?
        %h4 
          Você ainda não criou idéias. 
          = link_to "Começe agora!!", new_idea_path
      
      %br
      %h2 Idéias que participo
      - @user.registrations.each do |registration|
        .idea
          = image_tag registration.idea.logo.url(:medium), :width => "140"
          %h2= link_to registration.idea.title
          %p= registration.idea.short_description

app/views/welcome/quem_somos.html.haml
.row
  .content.span12

    %h2
      Desenvolvimento
    %p
      Eduardo Fiorezi, Anézio Marques e Rodrigo Reginato
      = link_to "da empresa de desenvolvimento de sistemas de Londrina hooppe.com", "http://hooppe.com"
    %p
      Flávio Granero do 
      = link_to "Tower CRM - Sistema para imobiliárias ", "http://towercrm.com.br/"
    
    %h2
      Design
    %p
      Renato Moriama da
      = link_to "Hanabi Design", "http://www.hanabidesign.com.br/"
    
    %h2
      Idealizadora
    %p
      Alexandra Yusiasu Dos Santos da
      = link_to "Aldeira Coworking - Londrina", "http://www.aldeiaco.com.br/londrina/"

    %h2
      Coordenador do projeto
    %p
      Daniel Kossmann da
      = link_to "spirallab", "http://www.spirallab.com.br/"